apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cultural-repo-joai-project-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: cultural-repo-joai-project-pv
