apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa-backend.yaml
  - hpa.yaml
  - deployment.yaml
  - deployment-backend.yaml
  - deployment-joai-project.yaml
  - deployment-nginx-media.yaml
  - ingress-backend.yaml
  - ingress-frontend.yaml
  # - ingress-backend-wildcard.yaml
  # - ingress-frontend-wildcard.yaml
  - ingress-joai-project.yaml
  - ingress.yaml
  - service-backend.yaml
  - service-joai-project.yaml
  - service.yaml
  - service-postgres.yaml
  - service-nginx-media.yaml
  - media-pv.yaml
  - media-pvc.yaml
  - joai-project-pv.yaml
  - joai-project-pvc.yaml
  - postgres-pvc.yaml
  - postgres-pv.yaml
  - postgres.yaml
  - backup-cronjob.yaml
  - restore-cronjob.yaml
  - backup-pv.yaml
  - backup-pvc.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - base=true
      - DEBUG=0
      - SQL_ENGINE='django_tenants.postgresql_backend'
      - SQL_HOST=postgres
      - SQL_DATABASE=cultural_repo_database
      - SQL_PORT=5432

  - name: frontend-config
    literals:
      - base=true

  - name: nginx-config
    files:
      - configs/default.conf

  - name: joai-project-config
    literals:
      - base=true

  - name: backup-config
    literals:
      - base=true
      - DB_HOST=prefix-postgres-suffix
      - DB_PORT=5432
      - DB_NAME=database-name
      - DB_TYPE=postgres
      - ROOT_BACKUP_FOLDER_ID=1ZpBe-VFK3RkemL0y0TpcQUUxTCkLcWwI
      - MAX_BACKUP_FOLDER_COUNT=5
      - CLIENT_NAME=client
      - APP_NAME=app-name
      - UPLOAD_TO_GOOGLE_DRIVE=FALSE

secretGenerator:
  - name: postgres-secret
    literals:
      - username=cultural_repo_db_user2022
      - password=?.cultural_repo.srv.dev@123?
