apiVersion: batch/v1
kind: CronJob
metadata:
  name: restore-cron-job
spec:
  schedule: "0 0 31 2 1"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: gitlab-registry-credentials
          volumes:
            - name: restore-volume
              persistentVolumeClaim:
                claimName: restore-pvc
            - name: media-volume-mount
              persistentVolumeClaim:
                claimName: cultural-repo-media-pvc
          containers:
            - name: restore-job-pod
              image: registry.gitlab.com/panos.soilem/gitlabregistries/web-app-backup-main:latest
              imagePullPolicy: Always
              volumeMounts:
                - name: restore-volume
                  mountPath: /data_to_restore
                - name: media-volume-mount
                  mountPath: /media_folder
              args:
                - /bin/bash
                - -c
                - bash restore.sh;
              envFrom:
                - configMapRef:
                    name: backup-config
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: username
                      optional: false
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: password
                      optional: false

          restartPolicy: OnFailure

      backoffLimit: 3
