---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cultural-repo-joai-project-production
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cultural-repo-joai-project-production
  policy:
    semver:
      range: 1.0.x

