---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cultural-repo-frontend-production
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cultural-repo-frontend-production
  filterTags:
    pattern: ^vatopedi-(?P<version>.*)$
    extract: $version
  policy:
    semver:
      range: '1.0.x'

