apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cultural-repo-web-staging
nameSuffix: -staging
resources:
  - ../../base
  - ../../../../secrets/gitlab_registry_secret.yml
  - namespace.yaml
patchesStrategicMerge:
  - hpa.yaml
  - ingress.yaml
  - deployment.yaml
  - hpa-backend.yaml
  - ingress-backend.yaml
  - deployment-backend.yaml
  - media-pv.yaml
  - postgres-pv.yaml
  - joai-project-pv.yaml
configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
    - DEBUG=1
    - ALLOWED_HOSTS=api.stg.repo.skopelos.gr,.api.stg.repo.skopelos.gr
    - APP_DOMAINS=api.stg.repo.skopelos.gr
    - SECRET_KEY='cultural-repo-stg-)lo8&f=(3jt3)h(gldd3y##fgqor&ipnv5zwge303g5$jy_68#dkjshwgved'
    - SQL_HOST=postgres-staging

  - name: frontend-config
    behavior: merge
    literals:
    - BACKEND_URL=api.stg.repo.skopelos.gr
    - HTTP=https
    - VIRTUAL_HOST=stg.repo.skopelos.gr