apiVersion: v1
kind: PersistentVolume
metadata:
  name: cultural-repo-media-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /cultural-repo/staging/media
    type: DirectoryOrCreate
