---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cultural-repo-backend-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cultural-repo-backend-staging
  policy:
    semver:
      range: 1.0.x

