---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: cultural-repo-frontend-staging
  namespace: flux-system
spec:
  interval: 1m0s
  image: registry.gitlab.com/panos.soilem/comic-registry/staging/frontend
  secretRef:
    name: gitlab-registry-credentials

