---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: client-base
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: comic-template-infrastructure
  wait: true
  path: ./clusters/client-base
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
