apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-hetzner-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: panos@codesaber.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-hetzner-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.vatopedianheritage.gr
            solverName: hetzner
            config:
              secretName: hetzner-secret
              zoneName: vatopedianheritage.gr
              apiUrl: https://dns.hetzner.com/api/v1
