apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare-cluster-issuer
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: panos@codesaber.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            email: panos.soilem@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsZones:
            - "repo.vatopedianheritage.gr"
