apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 1m
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner
  # url: https://mecodia.github.io/cert-manager-webhook-hetzner



---


apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      version: 'x.x.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: cert-manager
      interval: 1m
  values:
    groupName: 'acme.vatopedianheritage.gr'
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager