apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  hostPath:
    path: /cultural-repo/production/backups
    type: DirectoryOrCreate


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: restore-pv
spec:
  hostPath:
    path: /cultural-repo/production/restore
    type: DirectoryOrCreate