apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultural-repo
spec:
  template:
    spec:
      containers:
      - name: cultural-repo-web
        image: registry.gitlab.com/panos.soilem/comic-registry/cultural-repo/frontend:vatopedi-v1.0.4 # {"$imagepolicy": "flux-system:cultural-repo-frontend-production"}
