apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultural-repo-backend
spec:
  template:
    spec:
      containers:
      - name: cultural-repo-backend
        image: registry.gitlab.com/panos.soilem/comic-registry/cultural-repo/backend:skopelos-v1.0.6 # {"$imagepolicy": "flux-system:cultural-repo-backend-production"}
