apiVersion: v1
kind: PersistentVolume
metadata:
  name: cultural-repo-joai-project-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /extra-volume/cultural-repo/production/joai-project-config
    type: DirectoryOrCreate
