apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cultural-repo-web-production
nameSuffix: -production
resources:
  - ../../base
  - ../../../../secrets/gitlab_registry_secret.yml
  - namespace.yaml
patchesStrategicMerge:
  - hpa.yaml
  - ingress.yaml
  - deployment.yaml
  - deployment-backend.yaml
  - deployment-joai-project.yaml
  - hpa-backend.yaml
  - ingress-backend.yaml
  - ingress-frontend.yaml
  # - ingress-backend-wildcard.yaml
  # - ingress-frontend-wildcard.yaml
  - ingress-joai-project.yaml
  - joai-project-pv.yaml
  - media-pv.yaml
  - postgres-pv.yaml
  - backup-pv.yaml
configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - ALLOWED_HOSTS=api.repo.vatopedianheritage.gr,.api.repo.vatopedianheritage.gr
      - APP_DOMAINS=api.repo.vatopedianheritage.gr
      # - DJANGO_CORS_ALLOWED_ORIGINS='https://app.repo.vatopedianheritage.gr'
      # - DJANGO_CORS_ORIGIN_WHITELIST='https://app.repo.vatopedianheritage.gr'
      - SECRET_KEY='cultural-repo-prod-@1*b@n_=%!r2y)!o^2hegt-sfv8%1b8tfvj$m2jhk#s#@-=hgfdghsjw'
      - FRONTEND_URL='https://app.repo.vatopedianheritage.gr'
      - SQL_HOST=postgres-production
      - EMAIL_USE_TLS=True
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=culturalrepo@gmail.com
      - EMAIL_HOST_PASSWORD=jqcrcsxqxbtaiwtj

  - name: frontend-config
    behavior: merge
    literals:
      - BACKEND_URL=api.repo.vatopedianheritage.gr
      - HTTP=https
      - FRONTEND_DOMAIN=app.repo.vatopedianheritage.gr

  - name: backup-config
    behavior: merge
    literals:
      - DB_HOST=postgres-production
      - DB_PORT=5432
      - DB_NAME=cultural_repo_database
      - DB_TYPE=postgres
      - ROOT_BACKUP_FOLDER_ID=1XFY1of36z6VTjDmrGtSqWCdLirzeoL8h
      - MAX_BACKUP_FOLDER_COUNT=1
      - CLIENT_NAME=vatopedi
      - APP_NAME=cultural-repo-production
